package com.myspace.baamturules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Diagnostic implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int age;
	private java.util.List<java.lang.String> diseases;
	private java.util.List<java.lang.String> symptoms;

	private java.lang.String profession;

	private java.lang.String observation;

	public Diagnostic() {
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.util.List<java.lang.String> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(java.util.List<java.lang.String> diseases) {
		this.diseases = diseases;
	}

	public java.util.List<java.lang.String> getSymptoms() {
		return this.symptoms;
	}

	public void setSymptoms(java.util.List<java.lang.String> symptoms) {
		this.symptoms = symptoms;
	}

	public java.lang.String getProfession() {
		return this.profession;
	}

	public void setProfession(java.lang.String profession) {
		this.profession = profession;
	}

	public java.lang.String getObservation() {
		return this.observation;
	}

	public void setObservation(java.lang.String observation) {
		this.observation = observation;
	}

	public Diagnostic(int age, java.util.List<java.lang.String> diseases,
			java.util.List<java.lang.String> symptoms,
			java.lang.String profession, java.lang.String observation) {
		this.age = age;
		this.diseases = diseases;
		this.symptoms = symptoms;
		this.profession = profession;
		this.observation = observation;
	}

}